var list = ["Baseer", "Ajmal", "Abdulraqeeb",];
var Notcoming = ["furaqan", "AbdulRaqeeb"];
list.push("Abdul");
list.pop();
list.pop();
console.log("Hey ".concat(list[0], " You guyse still invited"));
console.log("Hey ".concat(list[1], " You guyse still invited"));
console.log("  Sorry ".concat(Notcoming[0], " I cant Invite You Beacuse Ihave Not Enough space At Home"));
console.log(" ".concat(Notcoming[1], " Sorry dont come at My House i Dont Have Enough space At Home"));
console.log("Here is the List Of People Who Making dinner this night With Me: ".concat(list[0], " ").concat(list[1], " "));
console.log("Here is Number Of People ".concat(list.length));
