let MyfaVpLace : string[]=["Makkah","Maddina","USA","London","Tokeyo"]
console.log("Orignal Order")
console.log(MyfaVpLace)
console.log("Sorted array")
console.log([...MyfaVpLace].sort())
console.log(MyfaVpLace)
console.log([...MyfaVpLace].reverse())
console.log(MyfaVpLace)
MyfaVpLace.reverse()
console.log(MyfaVpLace)
MyfaVpLace.reverse()
console.log(MyfaVpLace)
MyfaVpLace.sort()
console.log(MyfaVpLace)
MyfaVpLace.sort().reverse()
console.log(MyfaVpLace)
